// tag::scala-doc[]
/** This Scala source file was generated by the Gradle 'init' task.
 */
// tag::source-code[]
package guidesamples

class Library {
  def someLibraryMethod(): Boolean = true
}
// end::source-code[]
// end::scala-doc[]
