== General content

This section contains miscellaneous guidelines for the content of the guides that are independent of any specific guide section.

=== Write in US English

US English is simply more common in technical writing and more users are familiar with it (probably).

=== Avoid idioms, colloquialisms or other cultural references

Gradle has an international audience, many of whom don't speak English as their first language. Although idioms and the like can inject color into a guide, they will often result in simple incomprehension due to the reader's lack of familiarity with a word or expression. Try to keep things clear and culturally-neutral.

=== Prefer 'you' over 'we' where appropriate

When walking a reader through something you want them to do, it's perfectly fine to use either the 'you' or 'we' forms. However, it's important to be consistent in order to avoid dissonance for the reader.

With that in mind, use 'you' when referring to actions the reader should do or has already done, or for things that they should have or will have. For example:

 - You will create a new project
 - When you ran this task, …
 - You should now have a package you can use in other projects
 - By following these instructions, you will have a complete build for …

The 'we' form should be limited to speaking from the perspective of the guide author or team, for example "we want to encourage you to experiment with this."

=== Use 'they' for gender-neutral 3rd person singular pronoun

You may occasionally refer to a third party, such as a build user or the user of an application, i.e. someone that is neither you nor the reader. When that happens and you want to use a pronoun, prefer 'they', 'them', 'their', etc. This avoids the problem of assigning a gender to that third party with 'he' or 'she'.

=== Refer to the Gradle User Manual and Gradle Language Reference

The first is to distinguish the user manual from the Gradle Guides project, while the second is because we want to deprecate the use of the term DSL when talking about that part of the reference documentation. It's not obvious to everyone what DSL means in this context.

Note that you should only capitalize the complete names, i.e. Gradle User Manual and Gradle Language Reference. You can also refer to them as the _user manual_ and _language reference_ once it's clear to the reader that you're referring to the Gradle ones.

=== Favor 'build script' over 'build file'

This is to ensure consistency across guides.

=== Use consistent terminology across prose, section headings and document titles

It can be confusing to the reader if different terms are used for the same thing. How are they supposed to know if you're talking about the same thing or not.

As an example, if a section heading talks about "assembling a library JAR", then the prose should not then say "building the project JAR file". Instead, go with "assembling the library JAR".

