== Getting Started Guides

The following guidelines explain the structure and required attributes of a Getting Started Guide.


=== Focus on a single task

Getting Started Guides take the reader through the minimum of steps—the equivalent of a hello-world example—required to complete a specific task. This is partially a value judgement, but ask yourself whether you can break down the proposed task into several tasks that still have value to the user on their own.

For example, should a guide include both building and publishing a JVM library? We think not because building the JAR has value in itself: the library can be used directly. Publishing is a common requirement for JVM library projects, but it's not an _absolute_ requirement. It's an additional task that readers will often want to complete.

=== Create a working build

The user should have a working build after following the steps of a Getting Started Guide.

=== Use a set grammar for the title

The title of the guide should work when prefixed with "Getting Started" and start with a present participle where possible. The title should also ensure that it represents a capability the reader will learn rather than a task that they perform.

For example, favor "Building JVM libraries" over "Building _a_ JVM library", since the capability is "I can build JVM libraries."

=== Use standard sections

A Getting Started Guide has a fixed outline:

 - What you'll build (or What you'll create)
 - What you'll need
 - <The guide's specific steps>
 - Summary
 - Next steps

External contributors will find these already in the skeleton project that they start with.

=== Structure as a sequence of steps to complete

Provide precise steps for the reader to follow, with commands and code that can be copied, pasted and executed. Each discrete step should have its own heading that takes the form of an imperative.

=== Keep it short

A reader should be able to complete a Getting Started Guide in 10-30 minues, including copying or writing the code and executing the build.

=== Demonstrate that the guide has been successfully completed

How does a user know that they followed the instructions correctly? Did they build something that works? A Getting Started Guide should always attempt to include a final step that _shows_ the user successful completion.

As an example, https://guides.gradle.org/gs-building-jvm-libraries/#consume_the_library_jar[Getting Started Building JVM Libraries] has the user creating a class with a `main()` method that uses the library they just built. The user is then shown how to compile and run the class with the library's JAR on the classpath.

=== Avoid unnecessary prior knowledge

Every Getting Started Guide is a worked example. One difficulty is thinking of an example that isn't tied to a specific domain, such as file hashing, security, web applications, etc. If you were to use such an example, you would then have to work out how much extra information you should provide in case the user isn't familiar with the requirements and terminology of that domain.

The example doesn't have to be useful in itself, so avoid one that requires unnecessary knowledge on the part of the user. On the other hand, if the task is specific to a domain, then assuming knowledge of that domain is expected. For example, if a guide's task relates to Docker, then use a Docker example and assume knowledge of what Docker is and the tools around it.

=== Avoid instructions or commands that aren't strictly necessary

Anything extra beyond the bare minimum acts as a potential distraction and digression from the main focus of the guide.

=== Call out to places with more information

Getting Started Guides are lean and shouldn't introduce discussion points if possible. However, they _should_ link to reliable external material—such as the Gradle User Manual—that covers important and relevant discussion points for the given task.

As an example, https://guides.gradle.org/gs-building-jvm-libraries/#assemble_the_library_jar[Getting Started Building JVM Libraries] uses the standard Java project structure but links to the user manual to explain what that structure is and how to configure it, since that's relevant information.

Such links can also go into the Next Steps section for relevant follow-on tasks. For example, users will often want to publish a JVM library after building it, so the above guide links to another guide covering that task.

=== Address application developers and automation engineers new to the topic, not necessarily new to Gradle

Getting Started Guides should not reproduce the same basic information on using the Gradle build tool. Assume that readers of your guide have at least read the more basic ones on writing custom tasks and building JVM libraries.

=== Prefer the indefinite article for prerequisites

This is with respect to software that the reader needs to have installed before going through the guide. Examples:

 - A Java Development Kit, version X or better
 - A Gradle distribution, version X or better

=== Include installation links for software prerequisites

It's all well and good telling a user what software to install, but it makes their lives much easier if those instructions also include links on how to do so.

=== Never underestimate the time required to complete the guide

Imagine you spend double the time completing a guide than is stated in the prerequisites. How would you feel? We want to avoid the potential for any negative reactions or feelings.

=== Provide links to relevant documentation in Next Steps

In many cases, a next step should link to another guide. In the cases where no suitable guide exists, link to the appropriate chapter or section of the User Manual. Otherwise we leave the reader stranded.

=== Add comments for desirable next steps that don't have suitable material

Following on from the previous guideline, we want to track and identify any content or guides that we think should exist for a Next Step. To do this, add an Asciidoc comment that links to the GitHub issue for that missing content:

[source]
----
////
// - link to Working with a multi-project build - gradle-guides/gradle-guides.github.io#10
////
----

