== Make guides testable

A testable guide is not a guide that shows readers how to add tests, but is one where the included code snippets and even the console output is validated during the building of the guide. Having guides testable, results in lower maintenance for guide authors, especially when new versions of Gradle come out. Familiarize yourself with Asciidoctor's use of link:https://asciidoctor.org/docs/user-manual/#include-directive[file include] and link:https://asciidoctor.org/docs/user-manual/#by-tagged-regions[include tags] as they play a key role for including code tested code snippets and console output.

There are two specific ways to make a guide testable. As an author you can select one of more of these methods. The exact ones you select will be determined by the context of the guide you are writing.

NOTE: You might still find references to `gradleRunner` in some guides, which is from the link:https://ysb33rorg.gitlab.io/gradleTest/[GradleRunner plugin]. Usage of this has been deprecated and current usages are being removed from all guides. Please do not use this, but rather follow the test methods as described next.

=== Test method 1: Include a test suite

Include a test suite in the project. When the guide has many code snippets. Place the test code in the `src/test` folder and follow the Gradle conventions for writing tests.

For your convenience apply the the `org.gradle.guides.test-jvm-code` plugin when the code under test is JVM-based. You can use the Spock Framework for the testing, but are not limited to that. Configure the tests in the usual `test` block.

Here is an example of a test environment that a guide author has created as part of validating a guide

.build.gradle
[source,groovy]
----
test {
    systemProperties 'HTTPSERVER_PORT' : 65000
    systemProperties 'TEMPLATE_DIR' : file('src/publicationTest').absolutePath

    inputs.dir 'src/publicationTest'  // <1>
}
----
<1> Ensure the test ran when the sources used internally by the test changed.

=== Test method 2: Include a full project for native guides

This is currently the best approach for guides about native projects. As the native support in Gradle is evolving no simplifying patterns about native guides have arisen yet. Even though some of the above steps might work for a native guide author, it is recommend to create a project in a gradle script and then apply it from the main `build.gradle` file. For convention place the project script in the `gradle` folder.

Here is an example of including a basic C++ project.

.gradle/cpp.gradle
[source,groovy]
----
apply plugin : 'cpp'

model {
    components {
        main(NativeExecutableSpec)
    }
}
----

Include this script in the main project.

.build.gradle
[source,groovy]
----
apply from: 'gradle/cpp.gradle'
----

Having the project script separate, make it easier to include code snippets back into the guide. It also leads to less clutter in the main `build.gradle` file, which main purpose it to express how the guide will be built.

