= Building a Java Library

This guide walks you through the process of using Gradle to creating a Java library project that produces a JAR (Java Archive).

== What you’ll build

You'll write a simple Java class and then use Gradle to compile and package it into a new library named `mylib`. The result will be a JAR file containing the compiled class and a default manifest file. Along the way, you'll configure Gradle to express the _version_ of the library in the name of the JAR file. When complete, you'll verify that the library is well-formed by consuming it in a basic command-line application.

== What you’ll need

 - About 5 minutes
 - A text editor
 - The http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java Development Kit] (JDK), version 1.7 or better
 - Gradle version 3.0 or better

== Create a new Java library project

Create a new project directory named `mylib` and initialize the directory structure that will hold your library classes.

[source,shell]
----
mkdir mylib
cd mylib
mkdir -p src/main/java/org/example/mylib
----

Now create `MyClass`.

[source,java]
.src/main/java/org/example/mylib/MyClass.java
----
package org.example.mylib;

public class MyClass {
}
----

Create `build.gradle` and apply Gradle's built-in `java` plugin.

[source,gradle]
.build.gradle
----
apply plugin: 'java'
----


[TIP]
====
TODO: Mention `gradle init --type java-library` for future reference
====

== Build the library

Run `gradle jar`.

----
$ gradle jar
:compileJava
:processResources UP-TO-DATE
:classes
:jar

BUILD SUCCESSFUL
----

 1. compiling the Java source code
 2. processing any resource files
 3. packaging everything up into a JAR file

----
$ ls build/libs/
mylib.jar
----

----
$ jar -tf build/libs/mylib.jar
META-INF/
META-INF/MANIFEST.MF
MyClass.class
----

== Configure the library

[source,groovy]
.build.gradle
----
apply plugin: 'java'

jar {
    version = '0.1.0'
}
----

----
$ gradle clean jar
:compileJava
:processResources UP-TO-DATE
:classes
:jar
----

----
$ ls build/libs/
mylib-0.1.0.jar
----

You now have a JAR file whose name includes the version and that you can use with other Java projects.

== Consume the library

[source,java]
.Main.java
----
import org.example.mylib.MyClass;

public class Main {
    public static void main(String... args) {
        System.out.printf("Hello, %s!\n", MyClass.class.getSimpleName());
    }
}
----

----
$ javac Main
Main.java:1: error: package org.example.mylib does not exist
import org.example.mylib.MyClass;
                        ^
Main.java:5: error: cannot find symbol
        System.out.printf("Hello, %s!\n", MyClass.class.getSimpleName());
                                          ^
  symbol:   class MyClass
  location: class Main
2 errors
----

----
$ java -classpath .:build/libs/mylib.jar Main
Hello, MyClass!
----

== Summary

== Next steps

////
 - Getting Started Publishing Java Libraries gradle/build-tool-web#42
 - Adding a Java library into a multi-project build?
 - Building Java command line apps and webapps?
 - Publishing?
 - Managing a different directory structure (e.g. Grails)?
////
