= Writing Gradle Plugins

This guide walks you through the process of creating reusable build logic in a Gradle plugin.

== What you'll build

You'll write a simple plugin class that applies some standard Java project configuration. You'll then use that plugin for a simple Java build.

== What you'll need

 - About 5 minutes
 - A text editor
 - A http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java Runtime Environment] (JRE), version 1.7 or better
 - Gradle version 3.0 or better

// Last item should link to whatever gradle/build-tool-web#102 comes up with

== Create a Java project

~TODO: Various options, such as `init` task, manual creation, follow the Getting Started Building Java Library, use a Lazybones template~

This project will both host and use the plugin you're about to create.

== Create the plugin

----
mkdir -p buildSrc/src/main/java/org/example/myplugin
----

Create the file `buildSrc/src/main/java/org/example/myplugin` and set its content to:

[source,java]
----
package org.example.myplugin;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.plugins.JavaPlugin;

public class MyJavaConventionPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getPlugins().apply(JavaPlugin.class);
        project.getRepositories().mavenCentral();
        project.getDependencies().add("testCompile", "junit:junit:4.12");
    }
}
----

This plugin is using the Gradle API to do exactly the same as this build file fragment:

[source,groovy]
----
apply plugin: "java"

repositories {
    mavenCentral()
}

dependencies {
    testCompile  "junit:junit:4.12"
}
----

The Gradle `Project` object is the entry point to the entire Gradle API.

TIP: Use the Gradle {dsl-ref}[DSL Reference] and {javadoc-ref}[Javadocs] to learn what you can do with the Gradle API. Start with the entry for {dsl-ref}org.gradle.api.Project.html[`Project`].

Now run the `help` task and notice how the class in `buildSrc` automatically gets compiled.

== Use the plugin in your Java project

Create/open the `build.gradle` file in your Java project and add the following line:

[source,groovy]
----
apply plugin: org.example.myplugin.MyJavaConventionPlugin
----

[NOTE]
====
You might not be aware of it but you are applying the plugin by type. `JavaConventionPlugin` is the fully qualified class of your plugin implementation. One of Groovy's language features is to make the http://groovy-lang.org/style-guide.html#_classes_as_first_class_citizens[`.class` suffix for the class definition optional]. That's why the code example doesn't show `JavaConventionPlugin.class`.
====

You can now run the build to compile, test and package your Java project:

----
$ gradle build
...
----

This doesn't look as tidy as when you apply plugins with the `plugins {}` block, but we can fix that by adding a plugin identifier.

== Add plugin identifier

// Link to {user-manual}custom_plugins.html#sec:creating_a_plugin_id[plugin identifier]

Add a `buildSrc/src/main/resources/META-INF/gradle-plugins/org.example.my-java.properties` file that contains the following:

----
implementation-class=org.example.myplugin.MyJavaConventionPlugin
----

You must put the properties file in the directory `META-INF/gradle-plugins` as Gradle will try to resolve the file from that specific location in the plugin JAR. Now that your plugin has an identifier, you can replace

[source,groovy]
----
apply plugin: org.example.myplugin.MyJavaConventionPlugin
----

with

[source,groovy]
----
plugins {
    id "org.example.my-java"
}
----

== Summary

~TODO: Write the summary!

== Next steps

 - Publish the plugin to plugin portal
 - Publish to private company repository
 - Functionally test the plugin
