= Getting Started Creating New Gradle Builds image:https://travis-ci.org/{repo-path}.svg?branch=master["Build Status", link="https://travis-ci.org/{repo-path}"]

When encountering a Gradle-based project for the first time, many developers don't know what Gradle can do for them. The purpose of this guide is to show some of the basic tasks that work in any Gradle build, regardless of type of project. In this guide, you'll create a trivial Gradle project, invoke some of the basic Gradle commands, and get a sense of how Gradle manages the project.

== What you'll need

* About NN minutes
* A text editor or IDE
* A Java Development Kit (JDK), version 1.7 or better (only necessary to run Gradle)
* A https://gradle.org/install[Gradle distribution], version {gradle-version} or better

== Create a project

You can start a new project simply by creating a `build.gradle` file and adding build logic to it. To keep this example as simple as possible, create a new directory and add an empty file called `build.gradle` to it.

NOTE: Shell commands will shown for Unix-based systems. Windows has analogous commands for each.

[listing]
----
$ mkdir basic-demo
$ cd basic-demo
$ touch build.gradle // <1>
----
<1> Create an empty file called `build.gradle`

== Run the `tasks` command

Gradle is a Domain-Specific Language (DSL) for building projects. As an object-oriented system, its API is made up of many classes and methods. The build file itself configures an instance of the `org.gradle.api.Project` class, which has many built-in properties and methods. From the `Project`, you have access to all of Gradle's features.

By default, the name of the build file is called `build.gradle`. A `Project` includes a collection of _tasks_, each of which performs some basic operation.

To see what tasks are available even in this otherwise empty project, run the `tasks` command at the command prompt.

[listing]
----
$ gradle tasks
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'basic-demo'.
components - Displays the components produced by root project 'basic-demo'. [incubating]
dependencies - Displays all dependencies declared in root project 'basic-demo'.
dependencyInsight - Displays the insight into a specific dependency in root project 'basic-demo'.
dependentComponents - Displays the dependent components of components in root project 'basic-demo'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'basic-demo'. [incubating]
projects - Displays the sub-projects of root project 'basic-demo'.
properties - Displays the properties of root project 'basic-demo'.
tasks - Displays the tasks runnable from root project 'basic-demo'.

To see all tasks and more detail, run gradle tasks --all

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL
----

As the output shows, Gradle tasks are organized into categories, like `Build Setup` or `Help`, and each has a name and an optional description. You can define your own (known as _ad hoc_) tasks, configure tasks provided by the Gradle library, or use tasks that are added by plugins.

== Generate a Gradle wrapper














If you are specifically interested in building *Java* applications, read the {guides}creating-java-applications[Getting Started Building Java Applications] guide. You should also read the {user-manual}tutorial_java_projects.html[Java Quickstart] chapter of the user manual to obtain a wide understanding.

To learn more about bootstrapping other kinds of popular Gradle builds, particularly if you want or need to do it by hand, follow these readings for the type of project you want:

.Documentation for other popular project types
* *C*, *C++*, *Assembler*, *Objective-c*, *Objective-c++*: {user-manual}native_software.html[Native builds]
* *Scala*: {user-manual}scala_plugin.html[Scala plugin]
* *Groovy*: {user-manual}tutorial_groovy_projects.html[Groovy quickstart]
* *Android*: http://tools.android.com/tech-docs/new-build-system/user-guide[Android userguide]

== Next Steps

=== Learn the key concepts

Gradle is a very powerful tool, which means you need a good understanding of the underlying model to create maintainable builds. Fortunately, there are just a few core concepts to understand:

* *Build phases*: read the first section of the {user-manual}build_lifecycle.html[build lifecycle chapter] for a description of these.
* *Properties*: The project API and {user-manual}writing_build_scripts.html[properties]
* *Tasks*: {user-manual}more_about_tasks.html[Tasks]
* *File handling*: {user-manual}working_with_files.html[File handling]
* *Dependency management*: {user-manual}artifact_dependencies_tutorial.html[Dependency management]

=== Understand multi-project builds

It's not uncommon in multi-project builds to have subprojects of different types, particularly when you have a polyglot project or a separate project for documentation.  If you don't see a need right now to create a multi-project build, then you can safely skip this step—it's easy to make the switch later on if necessary. But if you do want to split a project into multiple, dependent and independent modules, you will need to learn how to configure them and manage the inter-module relationships. That requires a much more in-depth understanding of the topic than was covered in the build user path. We recommend you read the entirety of the {user-manual}multi_project_builds.html[multi-project builds chapter] of the user guide.

=== Learn basics of Groovy

You can make a fair bit of progress with Gradle without learning the language that build scripts are written in, but ultimately you'll limit yourself if you don't learn the basics of Groovy. Head to the http://groovy-lang.org/learn.html[Groovy website] to find out what learning resources are available or simply check out the https://classroom.udacity.com/courses/ud867/lessons/3968239469/concepts/42963752880923[Groovy fundamentals and Groovy Closures] sections of the free Udacity course.
