= Gradle Guides Plugins image:https://travis-ci.org/gradle-guides/gradle-guides-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/gradle-guides/gradle-guides-plugin?branch=master"]

This is a collection of very opinionated plugins that support the authoring of guides for Gradle.

* `org.gradle.guides.base`: The base of all of the subsequent plugins.
* `org.gradle.guides.getting-started`: Used by all new Getting Started guides.
* `org.gradle.guides.topical`: Used by all new Topical guides.
* `org.gradle.guides.tutorial`: Used by all new Tutorials.
* `org.gradle.guides.test-jvm-code`: Used to test JVM-based code snippets.

== How do I use the plugins?

Each of the plugins generates a guide from Asciidoc source. They all share the same conventions:

- The source for the guide is located in `content/index.adoc`
- Run `./gradlew asciidoctor` to generate the guide into `build/html5/index.html`.
- Run `./gradlew viewGuide` to generate the guide and open it in the browser.

== Base plugin

* Adds `guide` extension.
* Adds `asciidoctor` task with appropriate defaults for guide authoring. This task is also linked into the build lifecycle.
* Adds `asciidoctorAttributes` task.
* Adds `publishGhPages` task for publishing guide to `gh-pages`. (Used on Travis).
* Adds special Travis CI support via the `travisci` block.
* Adds `checkLinks` task to check hyperlinks in generated pages. (In the current release only absolute URLs are supported).
* Adds `gradleRunner` task to allow automating one set of steps described in a guide.
* Adds docs-asciidoctor-extensions library responsible for injecting navigation and CSS/JS

=== The guide extension

This `GuidesExtension` always has to be configured for a guide. (The initial repository generation process will probably provide a suitable default).

[source,kotlin]
----
guide {
    repoPath = "gradle-guides/creating-multi-project-builds" // <1>
}
----
<1> Set the GitHub URL after `github.com`.

=== The asciidoctorAttributes task

This task tells guide authors which Asciidoctor attributes are passed down from Gradle to the `asciidoctor` task

[listing]
----
$ ./gradlew asciidoctorAttributes

:asciidoctorAttributes
Current Asciidoctor Attributes
==============================
source-highlighter: coderay
coderay-linenums-mode: table
imagesdir: images
stylesheet: null
linkcss: true
docinfodir: .
docinfo1:
icons: font
sectanchors: true
sectlinks: true
linkattrs: true
encoding: utf-8
idprefix:
toc: right
toclevels: 1
guides: https://guides.gradle.org
gradle-version: 3.5
user-manual-name: User Manual
user-manual: https://docs.gradle.org/3.5/userguide/
language-reference: https://docs.gradle.org/3.5/dsl/
api-reference: https://docs.gradle.org/3.5/javadoc/
repo-path: gradle-guides/creating-multi-project-builds
----

== Test JVM Code plugin

* Adds `groovy` plugin, as well Spock Framework so that JVM code snippets can be tested.
* Adds `samples` convention.

=== Samples convention

Samples code can be placed in `src/samples/code` and expected output in `src/samples/output` i.e.

```
.
└── samples
    ├── code
    └── output
```

These files can be accessed from test code via system property `samplesDir`.

They can also be accessed from Asciidoc documents via the `{samplescodedir}` and `{samplesoutputdir}` attributes.

== Getting Started plugin

This should be applied in the authoring of all new Getting Started guides

== Topical plugin

This should be applied in the authoring of all new Topical guides

== Tutorial plugin

This should be applied in the authoring of all new Topical guides
