= Getting Started Writing Gradle Tasks

This guide will walk you through the creation of a custom Gradle task exploring
a number of key concepts that make Gradle tasks so powerful.

////
Need to refer and distinguish task types that are shipped by Gradle or acquired via plugins.
Explain this is a custom task.
////

== What you'll build

////
Te reader is not really building anything, rather just learning about custom tasks.
Maybe change the section to be called "What you'll learn". ??
////

== What you’ll need

* About 20 minutes
* A text editor or IDE
* A Java Development Kit (JDK), version 1.7 or better
* A {user-manual}/installation.html#sec:download[Gradle distribution], version {gradle-version} or better

== Create a custom task

////
Use the section to describe task creation and explain the syntax.

[source,groovy]
----
task hello {
  doLast { // <1>
      println 'Hello, World'
  }
}
----
<1>
////

== Actions

////
Describe how actions relate to tasks and cover doFirst, doLast
////

=== Left-shift operator is deprecated

////
Need to show an example of << and tell people not to use it.
Explain why it has been deprecated.
////

// Need a better title here
== Inputs & outputs

////
Use example of reading greeting from a file and show how this will affect
behaviour. I believe this is an important part of the journey. This is not
covered in the user manual, but it has been the source of numerous questions
on the forum.

A little explanation (not too detailed) of up to date checks should be in order.
We are not covering enabled/onlyIf/outputs.upToDateWhen just inputs, outputs.
Also I am not even sure whether inputs.properties schould be in scope.
////


== Limitation of custom tasks

////
Need to mention items like below as this can be dovetailed to next steps.

* Logic cannot be re-used
* More work to set it up to behave nicely
////

== Summary

That's it! You've worked through the steps necessary to create a custom Gradle Task. You should now understand the basic of actions, inputs, outputs and up-to-date checks for Gradle tasks.

== Next steps

////
Need to reference:
* Plugins getting started
* Task javadoc
////

== Help improve this guide

Have feedback or a question? Found a typo? Like all Gradle guides, help is just a GitHub Issue away. Please add an issue or pull request to the https://github.com/{repo-path}/[{repo-path}] and we'll get back to you.
