/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Swift project to get you started.
 * For more details take a look at the Building Swift applications and libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6-20190718104724+0000/userguide/building_swift_projects.html
 */

plugins {
    // Apply the swift-library plugin to add support for building Swift libraries
    `swift-library`

    // Apply the xctest plugin to add support for building and running Swift test executables (Linux) or bundles (macOS)
    xctest
}

// Set the target operating system and architecture for this library
library {
    targetMachines.add(machines.macOS.x86_64)
}
