== Debugging and diagnosing cache misses

For using task output caching efficiently it is essential to keep the balance between specifying all the inputs to your
tasks while not over-specifying them. If you don't specify enough of your inputs then your build will be incorrect and you
will share outputs between tasks that should have had a different output. If you specify unnecessary inputs to your tasks,
 you will have cache misses while you could have reused earlier outputs.
 For Gradle's built-in tasks we prefer to err on the side of correctness and we suggest that you do the same.

This chapter is about finding out why a cache miss was happening. If you have a cache hit which you didn't expect we
suggest to declare whatever change you expected to trigger the cache miss as an input to the task.

=== How to find errors

- Run build with no changes to see if caching still works
- Record graphs of execution times and see if it makes sense to you
- Look a certain types of changes and see if the expected tasks are cached

=== Helpful data for diagnosing a cache miss

A cache miss happens when Gradle calculates a build cache key for a task which is different from any of the build cache keys in the cache.
Only comparing the build cache key on its own does not give much information, so we need to look at some finer grained data to be able to diagnose the cache miss.
All the things influencing the build cache key can be found in the {user-manual}build_cache.html#sec:task_output_caching_details[userguide].

Basically, we can compare the following data, listed from coarse grained to fine grained:

- Build cache keys
- Task and Task action implementation inputs
  - classloader hash
  - class name
- Individual task property input hashes
- Hashes of files which are part of task input properties

Currently, the build cache key for the task is logged at the info level,
while information down to the individual input property level is available in the debug log:

....
Appending taskClass to build cache key: org.gradle.api.tasks.compile.JavaCompile_Decorated
Appending classLoaderHash to build cache key: da6eca52100422099189290bf68f200a
Appending actionType to build cache key: org.gradle.api.internal.project.taskfactory.AbstractOutputPropertyAnnotationHandler$2$1
Appending actionClassLoaderHash to build cache key: 2cdf3f9202925b5befa161030ab43724
Appending actionType to build cache key: org.gradle.api.internal.project.taskfactory.TaskClassValidator
.
.
.
Appending inputPropertyHash for 'classpath' to build cache key: 2b6ab53aa11d4a7d4a1f95a8f78f4d7c
Appending inputPropertyHash for 'effectiveAnnotationProcessorPath' to build cache key: d41d8cd98f00b204e9800998ecf8427e
Appending inputPropertyHash for 'options.sourcepath' to build cache key: d41d8cd98f00b204e9800998ecf8427e
Appending inputPropertyHash for 'source' to build cache key: f6ba49b2466f0090272c43ac5f54ec1d
Appending outputPropertyName to build cache key: destinationDir
Build cache key for task ':compileJava' is 2b220117efa6710f7ab191a0bbe48c00
....

If you want to go into the details of finding out e.g. which classes and jar files constitute the `classpath` for the `compileJava`
task you need to resort to comparing those files on disks yourself.

Luckily, you do not have to capture this data yourself - the build scan plugin already takes care of this for you.
This means that Gradle Enterprise already has the necessary data to diagnose the cache miss when using the build scan plugin.

=== Diagnosing the reasons for a cache miss

Having the data from the last section at hand, you should be able to diagnose why the outputs of a certain task were not found in the build cache.
Since you were expecting the task to be cached, you should be able to pinpoint a build which would have produced the artifact under question.

At first, you should check if the implementation of the task changed. This would mean checking the class names and classloader hashes
for the task class itself and for each of its action. If there is a change, this means that the build script, `buildSrc` or the Gradle version has changed.

If the implementation is the same, then you need to start comparing inputs between the two builds.
There should be at least one different input hash. If it is a simple value property, then the configuration of the task changed.
This can happen for example by

 - changing the build script,
 - conditionally configuring the task differently for CI or the developer builds,
 - depending on a system property or an environment variable for the task configuration,
 - or having an absolute path is part of the input.

If the changed property is a file property, then the reasons can be the same as for the change of a value property.
Most probably though a file on the filesystem changed in a way that Gradle detects a difference for this input.
The most common case will be that the source code was changed by a check in.
It is also possible that a file generated by Gradle changed, e.g. since it includes a timestamp.
Note that the Java version can also influence the output of the Java compiler.
If you did not expect the file to be an input to the task, then it is possible that you should alter the configuration of the task to not include it.
For example, having your integration test configuration including all the unit test classes as a dependency has the effect that all integration tests
are re-executed when a unit test changes.
Another option is that the task tracks absolute paths instead of relative paths and the location of the project directory changed on disk.

