= Building {cpp} Executables

This guide demonstrates how to create a minimalist {cpp} executable using Gradle's `cpp` plugin.

== What you'll need

* About +++<span class="time-to-complete-text"></span>+++
* A text editor
* A command prompt
* The Java Development Kit (JDK), version 1.7 or higher
* A https://gradle.org/install[Gradle distribution], version {gradle-version} or better
* An installed {cpp} compiler. See which link:{user-manual}native_software.html#native-binaries:tool-chain-support[{cpp} tool chains] are supported by Gradle and whether you have to do any {user-manual}native_software.html#sec:tool_chain_installation[installation configuration] for your platform.

== Layout

The first step is to create a folder for the new project and add a {user-manual}gradle_wrapper.html#sec:wrapper_generation[Gradle Wrapper] to the project.

[listing]
----
$ mkdir cpp-executable
$ cd cpp-executable
$ gradle wrapper // <1>

:wrapper

BUILD SUCCESSFUL
----
<1> This allows a version of Gradle to be locked to a project and henceforth you can use `./gradlew` instead of `gradle`.

Create a minimalist `build.gradle` file with the following content:

.build.gradle
[source,groovy]
----
include::{projdir}/gradle/cpp.gradle[]
----
<1> {cpp} projects are enabled via the `cpp` plugin
<2> All native build definitions are done within a `model` block.
<3> A native executable component is defined by a name - `main` in this case. This will determine the default location of source code, as well as the final name of the executable.
<4> An executable is specified by using {language-reference}org.gradle.nativeplatform.NativeExecutableSpec.html[NativeExecutableSpec].

If you run

[listing]
----
$ ./gradlew tasks
----

you will see in the output that Gradle has added a number of tasks

[listing]
----
installMainExecutable - Installs a development image of executable 'main:executable'
mainExecutable - Assembles executable 'main:executable'.

Build Dependents tasks
----------------------
assembleDependentsMain - Assemble dependents of native executable 'main'.
assembleDependentsMainExecutable - Assemble dependents of executable 'main:executable'.
buildDependentsMain - Build dependents of native executable 'main'.
buildDependentsMainExecutable - Build dependents of executable 'main:executable'.
----

Note the use of `Main` in the task names which are a direct deriviative of the component being called `main`.

== Add source code

By convention, {cpp} projects in Gradle will follow a more contemporary layout. This can be troublesome for you if you are used to building {cpp} code with build tools that do not use a convention-over-configuration approach. Rest assured that Gradle is very configurable in this regard and should you need to migrate a {cpp} project to Gradle you can consult the {user-manual}native_software.html#sec:cpp_sources[{cpp} sources] section of the User Guide.

In the `build.gradle` you have previsouly defined the executable component to be called `main`. By convention, this will means that Gradle will look in `src/main/cpp` for source files and non-exported header files. Create this folder

[listing]
----
$ mkdir -p src/main/cpp
----

and place a `main.cpp` an a `greeting.hpp` within.

.src/main/cpp/main.cpp
[source,cpp]
----
include::{codedir}/cpp/main.cpp[]
----
<1> The standard {cpp} headers wil be located via the compiler toolchain that Gradle uses
<2> Non-exported headers will be searched for relative to the specified {cpp} source folders. (In this case `src/main/cpp`).

.src/main/cpp/greeting.hpp
[source,cpp]
----
include::{codedir}/cpp/greeting.hpp[]
----

== Build your project

To build your project you can simply do `./gradlew build` as per usual, but if you specifically want to build the executable, run the task that Gradle has created for you:

[listing]
----
$ ./gradlew mainExecutable

:compileMainExecutableMainCpp // <1>
:linkMainExecutable // <2>
:mainExecutable

BUILD SUCCESSFUL
----
<1> To keep things tidy on the console, Gradle does not display compiler output. If you need to ever diagnose a compilation issue, the output from the compiler is stored in `build/tmp/compileMainExecutableMainCpp/output.txt`.
<2> In a similar fashion the output from the linker is written to `build/tmp/linkMainExecutable/output.txt`

Look inside the `build` folder and you will notice the appearance of a `exe` folder. By convention Gradle will place all executables in subfolders named according to the component name. In this case you will find your assembled executable in `build/exe/main` and it will be called `main` (or `main.exe` under Windows).

Now run your newly built executable.

[listing]
----
$ ./build/exe/main/main

Hello World
----

Congratulations! You have just built a {cpp} executable with Gradle.

== Summary

You have created an {cpp} project  that can be used as a foundation for something more substantial. In the process you saw:

* How to create a build script for {cpp} executables.
* Where to add source code by convention.
* How to build the executable without building the full project.

== Next Steps

* Testing using http://cunit.sourceforge.net[CUnit] or https://github.com/google/googletest[GoogleTest] is supported. Gradle will respectively create a matching {language-reference}org.gradle.nativeplatform.test.cunit.CUnitTestSuiteSpec.html[CUnitTestSuiteSpec] or {language-reference}org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteSpec.html[GoogleTestTestSuiteSpec] component for the executable you have defined in this guide. See  the {user-manual}native_software.html#native_binaries:cunit[CUnit support] and {user-manual}native_software.html#native_binaries:google_test[GoogleTest support] sections in  the User Guide for more details.
* As there is no 'standard' way of creating documentation for {cpp} projects, the `cpp` plugin does not offer a task to generate documentation. If you do use the popular http://www.stack.nl/~dimitri/doxygen[Doxygen] tool for documenting {cpp} code, you may want to have a look at the link:https://plugins.gradle.org/plugin/org.ysb33r.doxygen[Doxygen plugin] for Gradle


include::contribute[]
