= Using the Worker API

The Worker API provides the ability to break up the execution of a task action into discrete units of work
and then to execute that work concurrently and asynchronously.  This allows Gradle to fully utilizes the
resources available and complete builds faster.  This guide will walk you through the process of converting
an existing custom task to use the Worker API.

This guide assumes that you understand the basics of writing Gradle custom tasks.  Please consider working
through {guides}/writing-gradle-tasks[Writing Gradle Tasks] first.

== What you'll create

You'll start by creating a custom task class that generates MD5 hashes for a configurable set of files.  Then,
you'll convert this custom task to use the Worker API.  Then we'll explore running the task with different levels of
isolation.  In the process, you'll learn about the basics of the Worker API and the capabilities it provides.

== What you'll need

* About +++<span class="time-to-complete-text"></span>+++
* A text editor or IDE
* A Java Development Kit (JDK), version 1.7 or better
* A https://gradle.org/install[Gradle distribution], version {gradle-version} or better

== Create a custom task class

First, you'll need to create a custom task that generates MD5 hashes of a configurable set of files.

In a new directory, create a `buildSrc/build.gradle` file.

.buildSrc/build.gradle
[source,java]
----
include::{samplescodedir}/custom-task/buildSrc/build.gradle[]
----
<1> Your custom task class will use https://commons.apache.org/proper/commons-codec/[Apache Commons Codec] to generate
MD5 hashes.

TIP: If you are not familiar with `buildSrc`, this is a special directory that allows you to define and build
custom classes that should be available for use in your build script.  See
{user-manual}organizing_build_logic.html#sec:build_sources[the user manual] for further information.


Now, create a custom task class in your `buildSrc/src/main/java` directory.  You should name this class `CreateMD5`.

.buildSrc/src/main/java/CreateMD5.java
[source,java]
----
include::{samplescodedir}/custom-task/buildSrc/src/main/java/CreateMD5.java[]
----
<1> {api-reference}org/gradle/api/tasks/SourceTask.html[SourceTask] is a convenience type for tasks that operate on a
set of source files.
<2> The output of the task will go into a configured directory.
<3> The task iterates over all of the files defined as "source files" and creates an MD5 hash of each.
<4> Insert an artificial sleep to simulate hashing a large file (the sample files won't be that large).
<5> The MD5 hash of each file is written to the output directory into a file of the same name with an "md5" extension.

Next, create a build.gradle that implements your new `CreateMD5` task.

.build.gradle
[source,java]
----
include::{samplescodedir}/custom-task/build.gradle[]
----
<1> Apply the `base` plugin so that you'll have a `clean` task to use to remove the output.
<2> MD5 hash files will be written to `build/md5`.
<3> This task will generate MD5 hash files for every file in the `src` directory.

Now, you'll need some source to generate MD5 hashes from.  Create 3 files in the src directory:

.src/einstein.txt
[source,text]
----
include::{samplescodedir}/custom-task/src/einstein.txt[]
----

.src/feynman.txt
[source,text]
----
include::{samplescodedir}/custom-task/src/feynman.txt[]
----

.src/oppenheimer.txt
[source,text]
----
include::{samplescodedir}/custom-task/src/oppenheimer.txt[]
----

At this point, you can give your task a try:

[listing]
----
$ gradle md5
----

You should see output similar to:

[listing]
----
> Task :md5
Generating MD5 for einstein.txt...
Generating MD5 for feynman.txt...
Generating MD5 for oppenheimer.txt...


BUILD SUCCESSFUL in 12s
----

In the `build/md5` directory, you should now see corresponding files with an `md5` extension containing MD5 hashes of the
files from the src directory.  Notice that the task takes at least 9 seconds to run because it hashes each file one at a time
(i.e. 3 files at ~3 seconds a piece).

== Converting to the Worker API

Although this task processes each file in sequence, the processing of each file is independent of any other file.  It
would be really nice if this work was done in parallel and could take advantage of multiple processors.  This is where
the Worker API can help.

First, you'll need to refactor the part of your custom task that does the work for each individual file into a separate
class.  This class is your "unit of work" implementation and should implement `java.lang.Runnable`.

.buildSrc/src/main/java/GenerateMD5.java
[source,java]
----
include::{samplescodedir}/no-isolation/buildSrc/src/main/java/GenerateMD5.java[]
----
<1> This class must have a constructor annotated with `javax.inject.Inject`.
<2> The parameters to the constructor are the parameters of the individual unit of work.

Now, you should change your custom task class to submit work to the
{api-reference}org/gradle/workers/WorkerExecutor.html[WorkerExecutor] instead of doing the work itself.

.buildSrc/src/main/java/CreateMD5.java
[source,java]
----
include::{samplescodedir}/no-isolation/buildSrc/src/main/java/CreateMD5.java[]
----
<1> You'll need to have the {api-reference}org/gradle/workers/WorkerExecutor.html[WorkerExecutor] service in order
to submit your work.
<2> To get a {api-reference}org/gradle/workers/WorkerExecutor.html[WorkerExecutor], create a constructor annotated
with `javax.inject.Inject`.  Gradle will inject the
{api-reference}org/gradle/workers/WorkerExecutor.html[WorkerExecutor] at runtime when the task is created.
<3> When submitting the unit of work, specify the unit of work implementation, in this case `GenerateMD5`.
<4> For now, use an isolation mode of `NONE`.  We'll talk more about isolation modes later.
<5> For each unit of work, configure the `params` property appropriately.  These values should match up to the values
passed to the constructor of `GenerateMD5`.

At this point, you should be able to try your task again.

[listing]
----
$ gradle clean md5

> Task :md5
Generating MD5 for einstein.txt...
Generating MD5 for feynman.txt...
Generating MD5 for oppenheimer.txt...


BUILD SUCCESSFUL in 4s
----

The results should look the same as before, although the MD5 hash files may be generated in a different order due to
the fact that the units of work are executed in parallel.  One thing you should notice, however, is that the task runs
much faster.  This is because the Worker API executes the MD5 calculation for each file in parallel rather than in
sequence.

== Changing the isolation mode

The isolation mode controls how strongly Gradle will isolate items of work from each other as well as from
the rest of the Gradle runtime.  `IsolationMode.NONE` is the lowest level of isolation and will prevent a unit of work
from changing the project state.  `NONE` is the fastest isolation mode because it requires the least overhead to set
up the work item to execute, so you'll probably want to use this for simple cases.  However, it will use a single
shared classloader for all units of work.  This means that every unit of work must use the same classes and can
potentially affect each other through shared, static class state.  It also means that every unit of work must use the
same version of libraries that are on the buildscript classpath.  But what if you wanted the user to be able to
configure the task to run with a different (but compatible) version of the
https://commons.apache.org/proper/commons-codec/[Apache Commons Codec] library?  The Worker API allows
you to do that, too.

First, you'll want to change the dependency in `buildSrc/build.gradle` to be `compileOnly`.  This tells Gradle that it
should use this dependency when building the classes, but should not put it on the build script classpath.

.buildSrc/build.gradle
[source, groovy]
----
include::{samplescodedir}/classloader-isolation/buildSrc/build.gradle[]
----

Next, you'll want to change the `CreateMD5` task to allow the user to configure the version of the codec library that
they want to use.  It'll resolve the appropriate version of the library at runtime and configure the workers to use
this version.  The isolation mode `CLASSLOADER` tells Gradle to run this work in a thread with an isolated
classloader.

.buildSrc/src/main/java/CreateMD5.java
[source, groovy]
----
include::{samplescodedir}/classloader-isolation/buildSrc/src/main/java/CreateMD5.java[]
----
<1> Expose an input property for the codec library classpath.
<2> Configure the classpath on the
{api-reference}org/gradle/workers/WorkerConfiguration.html[WorkerConfiguration] when submitting the work item.

Next, you'll need to configure your build so that it has a repository to look up the codec version at task execution
time.  We'll also create a dependency to resolve our codec library from this repository.

.build.gradle
[source,java]
----
include::{samplescodedir}/classloader-isolation/build.gradle[]
----
<1> Add a repository to resolve the codec library - this can be a different repository than the one used to build the
`CreateMD5` task class.
<2> Add a configuration to hold our codec library version.
<3> Configure an alternate, compatible version of https://commons.apache.org/proper/commons-codec/[Apache Commons Codec].
<4> Configure the `md5` task to use the configuration as its classpath.  Note that the configuration will not be
resolved until the task is actually executed.

Now, if you run your task, it should work as expected using the configured version of the codec library:

[listing]
----
$ gradle clean md5

> Task :md5
Generating MD5 for einstein.txt...
Generating MD5 for feynman.txt...
Generating MD5 for oppenheimer.txt...


BUILD SUCCESSFUL in 9s
----

== Creating a Worker Daemon

Sometimes it is desirable to create even further isolation when executing items of work.  For instance, external
libraries may rely on certain system properties to be set which may conflict between work items.  Or a library might
not be compatible with the version of JDK that Gradle is running with and may need to be run with a different version.
The Worker API can accommodate this with an isolation mode of `PROCESS` that causes the work to execute in a separate
"worker daemon".  These worker daemon processes will persist across builds and can be reused during subsequent builds.
If system resources get low, however, Gradle will stop any unused worker daemons.

To utilize a worker daemon, you can simply change the isolation mode on the work items.  You may also want to
configure custom settings for the new process.

.buildSrc/src/main/java/CreateMD5.java
[source,java]
----
include::{samplescodedir}/process-isolation/buildSrc/src/main/java/CreateMD5.java[]
----
<1> Change the isolation mode to `PROCESS`.
<2> Set up the {api-reference}org/gradle/process/JavaForkOptions.html[JavaForkOptions] for the new process.

Now, you should be able to run your task, and it will work as expected but using worker daemons instead:

[listing]
----
$ gradle clean md5

> Task :md5
Generating MD5 for einstein.txt...
Generating MD5 for feynman.txt...
Generating MD5 for oppenheimer.txt...


BUILD SUCCESSFUL in 10s
----

Note that the execution time may be somewhat high.  This is because Gradle has to start a new process for each worker
daemon, which is expensive.  However, if you run your task again, you'll see that it runs much faster.  This is because
the worker daemon(s) started during the initial build have persisted and are available for use immediately during
subsequent builds.

[listing]
----
$ gradle clean md5

> Task :md5
Generating MD5 for einstein.txt...
Generating MD5 for feynman.txt...
Generating MD5 for oppenheimer.txt...


BUILD SUCCESSFUL in 5s
----

== Summary

In this guide you learned how to:

* Introduce the Worker API to an existing custom task to execute work in parallel with minimum isolation
* Use the Worker API classloader isolation mode to execute work using an isolated classpath
* Configure your task to isolate work even further in a separate "worker daemon" process


include::contribute[repo-path="gradle-guides/using-the-worker-api"]
