= Testing Gradle plugins
:toclevels: 2
:numbered:

With practice writing Gradle plugins comes easy especially with the knowledge of the link:https://guides.gradle.org/implementing-gradle-plugins/[Implementing Gradle plugins] guide under your belt. Part of every development process is testing whether that’s in a manual or automated fashion. The same is true for Gradle plugin code. Before letting any consumer use a plugin its functionality should be verified on different levels. In this guide you will learn how to debug plugin code during development. You will also getting to know the techniques used to write and execute different types of tests.

This guide assumes you have:

- Basic understanding of software engineering practices
- Knowledge of Gradle plugin implementation techniques
- Working knowledge in writing Java code

If you happen to be a beginner to Gradle please start by working through the link:https://gradle.org/guides#getting-started[Getting Started Guides on Gradle development] first while referencing the {user-manual}userguide.html[Gradle User Manual] to go deeper.

== Manual verification and debugging

=== Using composite builds

One way to test a plugin in a consuming project is to publish the plugin JAR file to a local repository and point the project it. Granted this technique is cumbersome - every change to the plugin code requires the developer to publish a new artifact.

With the introduction of the composite builds feature, plugin developers have a more powerful mechanism at their disposal. The standalone plugin project and the project consuming the plugin can be combined together into a single unit.

.build.gradle
[source,groovy]
----
----

== Defining and implementing appropriate tests types

=== The testing pyramid

=== Setting up dedicated source sets

----
.
└── src
    ├── functTest
    │   └── groovy      <= Functional tests
    ├── integTest
    │   └── groovy      <= Integration tests
    ├── main
    │   ├── java        <= Production source code
    │   └── resources   <= Production resource files
    └── test
        └── groovy      <= Unit tests
----

.integration-test.gradle
[source,groovy]
----
include::{samplescodedir}/url-verifier-plugin/gradle/integration-test.gradle[tags=test-type-setup]
----

=== Tooling for every test type

[cols="20%,80%",options="header"]
|======================
|Test type                               |Tooling
|<<unit-tests,Unit tests>>               |Any JVM-based test framework
|<<integration-tests,Integration tests>> |Any JVM-based test framework and Gradle's `ProjectBuilder` API
|<<functional-tests,Functional tests>>   |Any JVM-based test framework and Gradle TestKit
|======================

== Implementing tests

[[unit-tests]]
=== Unit tests

.HttpResponse.java
[source,java]
----
include::{samplescodedir}/url-verifier-plugin/src/main/java/org/gradle/sample/http/HttpResponse.java[]
----

.HttpResponseTest.groovy
[source,groovy]
----
include::{samplescodedir}/url-verifier-plugin/src/test/groovy/org/gradle/sample/http/HttpResponseTest.groovy[]
----

[[integration-tests]]
=== Integration tests

.DefaultHttpCaller.java
[source,java]
----
include::{samplescodedir}/url-verifier-plugin/src/main/java/org/gradle/sample/http/DefaultHttpCaller.java[]
----

.DefaultHttpCallerIntegrationTest.groovy
[source,groovy]
----
include::{samplescodedir}/url-verifier-plugin/src/integTest/groovy/org/gradle/sample/http/DefaultHttpCallerIntegrationTest.groovy[]
----

.UrlVerify.java
[source,java]
----
include::{samplescodedir}/url-verifier-plugin/src/main/java/org/gradle/sample/tasks/UrlVerify.java[]
----

.integration-test.gradle
[source,groovy]
----
include::{samplescodedir}/url-verifier-plugin/gradle/integration-test.gradle[tags=gradle-api]
----

.UrlVerifyIntegrationTest.groovy
[source,groovy]
----
include::{samplescodedir}/url-verifier-plugin/src/integTest/groovy/org/gradle/sample/tasks/UrlVerifyIntegrationTest.groovy[]
----

[[functional-tests]]
=== Functional tests

.UrlVerifierPlugin.java
[source,java]
----
include::{samplescodedir}/url-verifier-plugin/src/main/java/org/gradle/sample/UrlVerifierPlugin.java[]
----

.functional-test.gradle
[source,groovy]
----
include::{samplescodedir}/url-verifier-plugin/gradle/functional-test.gradle[tags=source-set-config]
----

.UrlVerifierPluginFunctionalTest.groovy
[source,groovy]
----
include::{samplescodedir}/url-verifier-plugin/src/functTest/groovy/org/gradle/sample/UrlVerifierPluginFunctionalTest.groovy[]
----

== Summary

Please let us know on the link:https://discuss.gradle.org/[Gradle forum] if you are still having difficulties understanding any of the covered testing strategies. Which one works the best for your plugin? Let us know!

Wrote an awesome plugin? Write a tweet to link:https://twitter.com/gradle[@gradle] with the link to the documentation or code.

== Next steps

Testing Gradle plugins builds upon best practices and development strategies. You may be interested in:

- link:https://guides.gradle.org/designing-gradle-plugins/[Designing Gradle plugins]
- link:https://guides.gradle.org/implementing-gradle-plugins/[Implementing Gradle plugins]
