= Consuming JVM Libraries

This guide demonstrates how to create a Java application which consumes an external library.

== What you'll build

You'll generate a Java application with the standard layout. You will then add a third-party library to your application, build it and package it. The final product will be a greeter application that produces an ASCII-art type greeting.

== What you'll need

* About [.time-to-complete-text]#NN#
* A text editor
* A command prompt
* The Java Development Kit (JDK), version 1.7 or higher
* A https://gradle.org/install[Gradle distribution], version {gradle-version} or better

== Create project

The first step is to create a folder for the new project and add a {user-manual}gradle_wrapper.html#sec:wrapper_generation[Gradle Wrapper] to the project.

[listing]
----
$ mkdir consuming-jvm-libraries
$ cd consuming-jvm-libraries
$ gradle wrapper // <1>

:wrapper

BUILD SUCCESSFUL
----
<1> This allows a version of Gradle to be locked to a project and henceforth you can use `./gradlew` instead of `gradle`.

TIP: Instead of using the built-in wrapper task, you may wish to use the `init` task from the {user-manual}build_init_plugin.html[Build Init] instead. This will create the initial project structure for you. See the {guides}/building-java-applications[Building Java Applications guide] for a detailed explanation of how to do this.

Create a `settings.gradle` file and set the name of the project. Doing this will ensure that the project builds with the correct name regardless of the name of the project root folder.

.settings.gradle
[source,groovy]
----
include::{example}/settings.gradle[]
----

Now create a `build.gradle` file and apply the Java plugin.

.build.gradle
[source,groovy]
----
include::{example}/build.gradle[tags=java]
----

That is enough to build a self-contained Java project, but you will be creating a greeter application, which will print the greeting in Ascii-art. For that an external library is required. Continue editing `build.gradle` and add a `repositories` block.

.build.gradle
[source,groovy]
----
include::{example}/build.gradle[tags=repositories]
----
<1> Use JCenter as the repository.

In order to find artifacts you have to tell Gradle where to look. Gradle supports two repository types - link:{user-manual}dependency_management.html#sub:maven_central[Maven] & link:{user-manual}dependency_management.html#sec:ivy_repositories[Ivy]. In addition Gradle supports simplified configuration for the most popular centralized repositories - JCenter, Maven Central and Google's Android repository. In this guide you are using JCenter as it has access to all of the repositories hosted on Maven Central as well as many more that are published to Bintray,

The next step is to tell Gradle which external artifacts you need for your projects. As you are doing and Ascii-art application you will be using https://github.com/lalyos/jfiglet[JFiglet]. Add a `dependencies` block to `build.gradle`.

.build.gradle
[source,groovy]
----
include::{example}/build.gradle[tags=dependencies]
----
<1> Add the JFiglet dependency to the `implementation` configuration.

Gradle supports a variety of link:{user-manual}dependency_management.html#sub:module_dependencies[notations], of which the one used above is probably the most popular. This uses what is most commonly known as Maven coordinates.

Adding a dependency has two parts: one is the dependency itself and the other is the configuration to which it is added. The latter term is used in Gradle to effectively group dependencies together by context. In this the configuration is called `implementation` and it is provided by the Java Plugin.

TIP: You can learn more about using configurations for your own custom purposes by studying the link:{language-reference}org.gradle.api.artifacts.ConfigurationContainer.html[ConfigurationContainer].

The purpose of the `implementation` configuration is the grouping of dependencies that are used by a library or application, but not exported via any of its APIs. As this is a stand-alone application, all dependencies can be placed in this configuration for purposes of application construction.

You can also inspect all of the dependencies you have added on a per-configuration basis, by using the `dependencies` task that is built into Gradle.

[listing.terminal]
----
./gradlew dependencies --configuration implementation # <1>

include::{gradle-outdir}/clean-dependencies/out.txt[]
----
<1> The `--configuration` parameter restricts inspection to a single configuration.

NOTE: If you are using Gradle 4.0 or later you may see less output from the console that you might see in this guide. This is because in this guide output is shown as when `--console-plain` is also passed to Gradle as a command-line. This is done to show the tasks that Gradle is executing.

== Create the application

Proceed to creating a `src/main/java` folder and place a `GreeterApp.java` file within that folder containing the following source code

.src/main/java/GreeterApp.java
[source,java]
----
include::{example}/src/main/java/GreeterApp.java[]
----

NOTE: Due to simplicity of this two line application, testing will be left from from this example.

Build your application by using the `assemble` task.

[listing.terminal]
----
$ ./gradlew assemble

include::{gradle-outdir}/clean-assemble/out.txt[]
----

As this is an application, it will be useful to distribute it. Edit `build.gradle` again and add the Application plugin.

.build.gradle
[source,groovy]
----
include::{example}/build.gradle[tags=application]
----
<1> The link:{user-manual}application_plugin.html[Application plugin] is a very useful plugin that allows you to bundle your aplpication along with all of its dependencies.
<2> This configures the entry point into the application, which needs to be a class with a class (static) method called `main`.

Finish building your application by using the `build` task.

[listing.terminal]
----
$ ./gradlew build

include::{gradle-outdir}/build/out.txt[]
----

If you inspect the `build/distributions` folder you will notice both `.zip` and `.tar` archives. This is the application ready for distribution. Now it is time to test your application manually. The Application plugin provides a useful `instalLDist`

[listing.terminal]
----
$ ./gradlew installDist

include::{gradle-outdir}/install/out.txt[]
----

Look in `build/install` where you should find a `greeterApp` folder containing `lib` and `bin` folders. I fyou look inthe `lib` folder you will see both your application and the JFiglet JARs.

Run the application by changing to the `build/install/greeterApp` folder and executing the application.

[listing.terminal]
----
$ cd build/install/greeterApp
$ ./bin/greeterApp Gradle

include::{gradle-outdir}/run/run.txt[]
----

Congratulations! You have just created an application which consumes a third-party library from an external repository.

== Licensing

Third-party JVM libraries are released under various licenses. It is important to always check the licenses of the libraries you use, including all of the libraries that are introduced via transitive dependencies, for compatibility.

For example the library that you used today is released under http://www.gnu.org/licenses/gpl-2.0.html[GPL 2.0]. This will mean that should you want to release the application you have just built, it will also need to be under GPL 2.0.

You can utilise Jeroen van Erp's excellent https://plugins.gradle.org/plugin/com.github.hierynomus.license[License plugin] to create a report on the licenses of all of the dependencies of your project.

== Summary

You now have JVM application that consumes an external library. In this process you saw:

* How to configure repositories and dependencies.
* Build an aplication consuming external dependencies.
* Distribute an application with all external dependencies.

== Next Steps

////
// TODO: If guide about artifact resolution is written, then this guide needs to point to that
////

* Read about using your own {user-manual}dependency_management.html#sub:maven_repo[Maven repository] installations
* Read about configuring link:{user-manual}dependency_management.html#sec:ivy_repositories[Ivy repositories].
* Read about finding artifacts without metadata in link:{user-manual}dependency_management.html#sec:flat_dir_resolver[local folders].
* Read about link:{user-manual}dependency_management.html#sec:finetuning_the_dependency_resolution_process[advanced artifact resolution] and how to deal with version & dependency conflicts.

// include::contribute[]
