= Building and Testing C++ Libraries

This guide shows how to

. Build a simple {cpp} library using the Gradle `cpp-library` plugin, and
. Build and Run generic unit tests using the `cpp-unit-test` plugin.

== What you'll need

* About +++<span class="time-to-complete-text"></span>+++
* A text editor
* A command prompt
* The Java Development Kit (JDK), version 1.8 or higher
* A https://gradle.org/install[Gradle distribution], version {gradle-version} or better
* An installed {cpp} compiler. See which link:{user-manual}cpp_plugins.html#cpp:tool-chain-support[{cpp} tool chains] are supported by Gradle and whether you have to do any {user-manual}cpp_plugins.html#cpp:tool_chain_installation[installation configuration] for your platform.

== Layout

The first step is to create a folder for the new project and add a {user-manual}gradle_wrapper.html#sec:wrapper_generation[Gradle Wrapper] to the project.

[listing]
----
$ mkdir building-and-testing-cpp-libraries
$ cd building-and-testing-cpp-libraries
$ gradle wrapper // <1>

:wrapper

BUILD SUCCESSFUL
----
<1> This allows a version of Gradle to be locked to a project and henceforth you can use `./gradlew` instead of `gradle`.

Create a `build.gradle` file that has the following content:

.build.gradle
[source,groovy]
----
include::{projdir}/gradle/cpp.gradle[]
----
<1> {cpp} projects are enabled via the `cpp-library` plugin
<2> C++ unit test binaries are built using the generic `cpp-unit-test` plugin
<3> Change the library binary names, the base name defaults to the project name
<4> Change the unit test binary names, the base name defaults to the project name followed by the `Test` suffix

There are a few things to note here

* The `cpp-library` plugin automatically generates library component configurable via `library` extension DSL.
* The `cpp-unit-test` plugin automatically generates a executable component that depends on the library. It also adds a new  _verification task_. The verification tasks are `check` tasks that assemble and test a binary. The unit test component configurable via the `unitTest` extension DSL.

== Add source code

In `build.gradle`, there are two components implicitly created. The `main` component is the library you will be building and the `test` component is a simple executable to consume this library for verfication purpose. The sources are structured as below

* `main` library - `src/main/cpp` for sources, `src/main/headers` for _non-exported header files_ and `src/main/public` for _exported header files_
* `test` executable - `src/test/cpp` for sources.

[listing]
----
mkdir -p src/main/cpp src/main/public
mkdir -p src/test/cpp
----

Place a `greeter.h` in `src/main/public` and a `greeter.cpp` in `src/main/cpp`.

.src/main/public/greeter.h
[source,cpp]
----
include::{projdir}/src/main/public/greeter.h[]
----

.src/main/cpp/greeter.cpp
[source,cpp]
----
include::{projdir}/src/main/cpp/greeter.cpp[]
----

Place a `greeter_test.cpp` under `src/test/cpp`.

.src/test/cpp/greeter_test.cpp
[source,cpp]
----
include::{projdir}/src/test/cpp/greeter_test.cpp[]
----

== Build the project

Gradle adds tasks to the build for only shared form of the library. To build build a static library, please refer to the https://github.com/gradle/native-samples/tree/master/cpp/static-library[static library sample].

To build the shared library you can simply do `./gradlew assemble` as per usual.

[listing]
----
$ ./gradlew assemble
----

[listing]
----
$ find build/lib/
build/lib/
build/lib/main
build/lib/main/debug
build/lib/main/debug/libgreeter.so
----

== Test the project

As mentioned earlier, the `cpp-unit-test` plugin automatically adds the test suite components and verification tasks to the project. When you run the `build` task, gradle runs the compile tasks for source code and the test suites.

It then runs the test suite binary as well. The test binary in this case will be named `greeterTest` and the task will be named `runTest`.

[listing.terminal]
----
$ ./gradlew build
:compileDebugCpp
:linkDebug
:assemble
:compileTestCpp
:linkTest
:installTest

:runTest
[test] returns the correct name length... pass

:test
:check
:build
----

You should see the output from the C++ test suite that you had written for the library as part of the output for the `build` task.

== Summary

You have created a {cpp} library and written unit tests for it. In doing so, you saw

* How to create gradle build scripts for {cpp} libraries.
* How to generate shared libraries from {cpp} sources.
* How to build and run a test suite

== Next Steps

* Make your way to the native samples repository to see the C++ plugins in action for common scenarios such as https://github.com/gradle/native-samples/tree/master/cpp/transitive-dependencies[transitive dependencies], https://github.com/gradle/native-samples/tree/master/cpp/swift-package-manager[custom source layout], and https://github.com/gradle/native-samples/tree/master/cpp/static-library[static library].

include::contribute[repo-path="gradle-guides/building-cpp-libraries"]
