= Building {cpp} Executables

This guide demonstrates how to create a minimalist {cpp} executable using Gradle's `cpp` plugin.

== What you'll need

* About +++<span class="time-to-complete-text"></span>+++
* A text editor
* A command prompt
* The Java Development Kit (JDK), version 1.8 or higher
* A https://gradle.org/install[Gradle distribution], version {gradle-version} or better
* An installed {cpp} compiler. See which link:{user-manual}cpp_plugins.html#cpp:tool-chain-support[{cpp} tool chains] are supported by Gradle and whether you have to do any {user-manual}cpp_plugins.html#cpp:tool_chain_installation[installation configuration] for your platform.

== Layout

The first step is to create a folder for the new project and add a {user-manual}gradle_wrapper.html#sec:wrapper_generation[Gradle Wrapper] to the project.

[listing]
----
$ mkdir cpp-executable
$ cd cpp-executable
$ gradle wrapper // <1>

:wrapper

BUILD SUCCESSFUL
----
<1> This allows a version of Gradle to be locked to a project and henceforth you can use `./gradlew` instead of `gradle`.

Create a minimalist `build.gradle` file with the following content:

.build.gradle
[source,groovy]
----
include::{projdir}/gradle/cpp.gradle[]
----
<1> {cpp} projects are enabled via the `cpp-application` plugin
<2> Change the application binary names, the base name defaults to the project name

== Add source code

By convention, {cpp} projects in Gradle will follow a more contemporary layout. This can be troublesome for you if you are used to building {cpp} code with build tools that do not use a convention-over-configuration approach. Rest assured that Gradle is very configurable in this regard and should you need to migrate a {cpp} project to Gradle you can consult the {user-manual}cpp_plugins.html#cpp:cpp_sources[{cpp} sources] section of the User Guide.

The executable component is called `main`. By convention, Gradle will look in `src/main/cpp` for source files and non-exported header files. Create this folder

[listing]
----
$ mkdir -p src/main/cpp
----

and place a `main.cpp` and a `greeting.hpp` within.

.src/main/cpp/main.cpp
[source,cpp]
----
include::{codedir}/cpp/main.cpp[]
----
<1> Non-exported headers will be searched for relative to the specified {cpp} source folders. (In this case `src/main/cpp`).
<2> The standard {cpp} headers wil be located via the compiler toolchain that Gradle uses

.src/main/cpp/greeting.h
[source,cpp]
----
include::{codedir}/cpp/greeting.h[]
----

== Build your project

To build your project you can simply do `./gradlew assemble` as per usual:

[listing]
----
$ ./gradlew assemble

:compileDebugCpp // <1>
:linkDebug // <2>
:assemble

BUILD SUCCESSFUL
----
<1> To keep things tidy on the console, Gradle does not display compiler output. If you need to ever diagnose a compilation issue, the output from the compiler is stored in `build/tmp/compileDebugCpp/output.txt`.
<2> In a similar fashion the output from the linker is written to `build/tmp/linkDebug/output.txt`

Look inside the `build` folder and you will notice the appearance of a `exe` folder. By convention Gradle will place all executables in subfolders named according to the component name. In this case you will find your assembled executable in `build/exe/main/debug` and it will be called `main` (or `main.exe` under Windows).

Now run your newly built executable.

[listing]
----
$ ./build/exe/main/debug/greeting

Hello World
----

Congratulations! You have just built a {cpp} executable with Gradle.

== Summary

You have created an {cpp} project  that can be used as a foundation for something more substantial. In the process you saw:

* How to create a build script for {cpp} executables.
* Where to add source code by convention.
* How to build the executable without building the full project.

== Next Steps

* Make your way to the native samples repository to see the C++ plugins in action for common scenarios such as https://github.com/gradle/native-samples/tree/master/cpp/transitive-dependencies[transitive dependencies] and https://github.com/gradle/native-samples/tree/master/cpp/swift-package-manager[custom source layout].

include::contribute[repo-path="gradle-guides/building-cpp-executables"]
