= Building C++ Libraries


== What you'll build

This guide shows how to build a simple {cpp} library using the Gradle `cpp` plugin.

== What you'll need

* About +++<span class="time-to-complete-text"></span>+++
* A text editor
* A command prompt
* The Java Development Kit (JDK), version 1.7 or higher
* A https://gradle.org/install[Gradle distribution], version {gradle-version} or better
* An installed {cpp} compiler. See which link:{user-manual}native_software.html#native-binaries:tool-chain-support[{cpp} tool chains] are supported by Gradle and whether you have to do any {user-manual}native_software.html#sec:tool_chain_installation[installation configuration] for your platform.

== Layout

The first step is to create a folder for the new project and add a {user-manual}gradle_wrapper.html#sec:wrapper_generation[Gradle Wrapper] to the project.

[listing]
----
$ mkdir building-cpp-libraries
$ cd building-cpp-libraries
$ gradle wrapper // <1>

:wrapper

BUILD SUCCESSFUL
----
<1> This allows a version of Gradle to be locked to a project and henceforth you can use `./gradlew` instead of `gradle`.

Create a `build.gradle` file that has the following content:

.build.gradle
[source,groovy]
----
include::{projdir}/gradle/cpp.gradle[]
----
<1> {cpp} libraries and binaries are built using the `cpp` plugin.
<2> Native builds use the `model` block
<3> Native libraries are specified as a component of type `NativeLibrarySpec` and defined by a name - `greeter` in this case.
<4> Native binaries are specified as a component of type `NativeBinarySpec` and defined by a name - `main` in this case.
<5> The `main` binary uses the `greeter` {c++} library and is specified using `cpp.lib`
<6> When using the VC++ compiler, the library methods should be declared with `__declspec(dllexport)` for shared library. This defines the macro `DLL_EXPORT` based on which the declaration is modified.

Now run

[listing]
----
$ ./gradlew tasks
----

You should see a number of tasks that has been added by Gradle

[listing]
----
greeterSharedLibrary - Assembles shared library 'greeter:sharedLibrary'.
greeterStaticLibrary - Assembles static library 'greeter:staticLibrary'.

Build Dependents tasks
----------------------
assembleDependentsGreeter - Assemble dependents of native library 'greeter'.
assembleDependentsGreeterSharedLibrary - Assemble dependents of shared library 'greeter:sharedLibrary'.
assembleDependentsGreeterStaticLibrary - Assemble dependents of static library 'greeter:staticLibrary'.
buildDependentsGreeter - Build dependents of native library 'greeter'.
buildDependentsGreeterSharedLibrary - Build dependents of shared library 'greeter:sharedLibrary'.
buildDependentsGreeterStaticLibrary - Build dependents of static library 'greeter:staticLibrary'.
----

There are two things to note here

* The names `Greeter` and `Main` in the task names are derived from the names of the components defined in `build.gradle`.
* The `NativeLibrarySpec`, by default, generates both static and shared(dynamic) libraries.  By default, the shared library is used by the binaries that use this library

== Add source code

In build.gradle, there are two components. `greeter` is the library you will be building and `main` is a simple executable to consume this library. The sources are structured as below

* `greeter` library - `src/greeter/cpp` for sources and _non-exported header files_ and `src/greeter/headers` for _exported header files_
* `main` binary - `src/main/cpp` for sources.

In general, the sources are located at `src/{name}/cpp` where `name` is the name of the component

[listing]
----
mkdir -p src/greeter/cpp src/greeter/headers
mkdir -p src/main/cpp
----

Place a `greeter.hpp` in `src/greeter/headers` and a `greeter.cpp` in `src/greeter/cpp`.

.src/greeter/headers/greeter.hpp
[source,cpp]
----
include::{projdir}/src/greeter/headers/greeter.hpp[]
----

.src/greeter/cpp/greeter.cpp
[source,cpp]
----
include::{projdir}/src/greeter/cpp/greeter.cpp[]
----

Now place a `greeting.cpp` under `src/main/cpp`.

.src/main/cpp/greeting.cpp
[source,cpp]
----
include::{projdir}/src/main/cpp/greeting.cpp[]
----

== Build the project

Gradle adds tasks to the build for both static and shared form of the library. To build just the static library, run

[listing]
----
$ ./gradlew greeterStaticLibrary
:compileGreeterStaticLibraryGreeterCpp // <1>
:createGreeterStaticLibrary
:greeterStaticLibrary

BUILD SUCCESSFUL

----
<1> Gradle does not show the compiler commands or the compiler output in order to keep the output from Gradle itself clean. But the compiler output can be found in `build/tmp/compileGreeterStaticLibraryGreeterCpp/output.txt` and the compiler flags can be found in `build/tmp/compileGreeterStaticLibraryGreeterCpp/options.txt`

This builds the static library under `build/libs/greeter/static`

[listing]
----
$ find build/libs/
build/libs/
build/libs/greeter
build/libs/greeter/static
build/libs/greeter/static/libgreeter.a
----

In a similar fashion, the shared library can be generated by running

[listing]
----
$ ./gradlew greeterSharedLibrary
----

[listing]
----
$ find build/libs/
build/libs/
build/libs/greeter
build/libs/greeter/shared
build/libs/greeter/shared/libgreeter.so
build/libs/greeter/static
build/libs/greeter/static/libgreeter.a
----

Since the `main` component depends on the `greeter` library, running the `mainExecutable` task will generate the static and shared libraries and the binary as well.

[listing]
----
$ ./gradlew mainExecutable
:compileMainExecutableMainCpp
:compileGreeterSharedLibraryGreeterCpp
:linkGreeterSharedLibrary
:greeterSharedLibrary
:linkMainExecutable
:mainExecutable

BUILD SUCCESSFUL
----

You can run the binary that uses this library (you need to set the LD_LIBRARY_PATH as needed so that the shared library can be located).

[listing]
----
$ LD_LIBRARY_PATH=build/libs/greeter/shared/ ./build/exe/main/main 
Hello, Gradle User
----

== Summary

You have created a {cpp} library (both static and shared). In doing so, you saw

* How to create gradle build scripts for {cpp} libraries.
* How to generate static and/or shared libraries from {cpp} soruces.
* How to use our library in a {cpp} binary.
