package org.gradle.guides

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generate the Developer Certificate of Origin GitHub Application configuration file.
 *
 * @since 0.15.8
 */
abstract class GenerateDeveloperCertificateOfOriginConfiguration extends DefaultTask {
    @OutputFile
    abstract RegularFileProperty getOutputFile()

    @TaskAction
    private doGenerate() {
        outputFile.asFile.get().text = """# File auto-generated by https://github.com/gradle-guides/gradle-guides-plugin/tree/master/src/main/groovy/${GenerateDeveloperCertificateOfOriginConfiguration.canonicalName.replaceAll('\\.', '/')}.groovy
# Do not modify unless the '${this.path}' tasks is disabled in the build script.

# Disable sign-off checking for members of the Gradle GitHub organization
require:
  members: false
"""
    }
}
