/*
 * Copyright 2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gradle.guides

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generates the .gitignore configuration file for guide repository.
 *
 * @since 0.15.8
 */
abstract class GenerateGitIgnoreConfiguration extends DefaultTask {
    @OutputFile
    abstract RegularFileProperty getOutputFile()

    @TaskAction
    private void doGenerate() {
        outputFile.asFile.get().text = """# File auto-generated by https://github.com/gradle-guides/gradle-guides-plugin/tree/master/src/main/groovy/${GenerateGitIgnoreConfiguration.canonicalName.replaceAll('\\.', '/')}.groovy
# Do not modify unless the '${this.path}' tasks is disabled in the build script.

# Gradle
.gradle/
build/

# Vim
*.sw?

# IntelliJ
.idea/
*.iml

# macOS
.DS_Store
"""
    }
}
