package org.gradle.guides

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.TaskAction

/**
 * Generates the .gitignore configuration file for guide repository.
 *
 * @since 0.15.8
 */
abstract class GenerateGitIgnoreConfiguration extends DefaultTask {
    abstract RegularFileProperty getOutputFile()

    @TaskAction
    private void doGenerate() {
        outputFile.asFile.get().text = """# File auto-generated by https://github.com/gradle-guides/gradle-guides-plugin/tree/master/src/main/groovy/${GenerateGitIgnoreConfiguration.canonicalName.replaceAll('\\.', '/')}.groovy
# Do not modify unless the '${this.path}' tasks is disabled in the build script.

# Gradle
.gradle/
build/

# Vim
*.sw?

# IntelliJ
.idea/
*.iml

# macOS
.DS_Store
"""
    }
}
