/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "building-cpp-libraries.h"

std::string building_cpp_libraries::Greeter::greeting() {
    return std::string("Hello, World!");
}
