/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "building-cpp-libraries.h"
#include <cassert>

int main() {
    building_cpp_libraries::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
