/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample CPP project to get you started.
 */

plugins {
    // Apply the cpp-library plugin to add support for building CPP libraries
    `cpp-library`

    // Apply the cpp-unit-test plugin to add support for building and running CPP test executables
    `cpp-unit-test`
}

// Set the target operating system and architecture for this library
library {
    targetMachines.add(machines.macOS.x86_64)
}
