// tag::groovy-doc[]
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
// tag::source-code[]
package demo

class Library {
    boolean someLibraryMethod() {
        true
    }
}
// end::source-code[]
// end::groovy-doc[]
