// tag::java-doc[]
/**
 * This java source file was generated by the Gradle 'init' task.
 */
// tag::source-code[]
package demo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
// end::source-code[]
// end::java-doc[]
