/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef BUILDING_CPP_LIBRARIES_H
#define BUILDING_CPP_LIBRARIES_H

#ifdef _WIN32
#define BUILDING_CPP_LIBRARIES_EXPORT_FUNC __declspec(dllexport)
#else
#define BUILDING_CPP_LIBRARIES_EXPORT_FUNC
#endif

#include <string>

namespace building_cpp_libraries {
    class Greeter {
        public:
        std::string BUILDING_CPP_LIBRARIES_EXPORT_FUNC greeting();
    };
}

#endif
